INSERT INTO plan_categories (name, slug, sort_order, image)
SELECT 'Modern Villas', 'modern-villas', (SELECT COALESCE(MAX(sort_order), -1) + 1 FROM plan_categories p2), NULL
WHERE NOT EXISTS (SELECT 1 FROM plan_categories WHERE slug = 'modern-villas');

INSERT INTO properties (title, slug, price, plan_number, bedrooms, bathrooms, stories, garage_bays, area_sqft, width_ft, depth_ft, foundation_type, roof_type, exterior_material, category, featured, description, features) VALUES
('The Meridian Villa', 'the-meridian-villa', 1250.00, 'MV-101', 4, 3.5, 2, 2, 3200.00, 68, 58, 'Slab', 'Flat Roof', 'Stucco & Glass', 'Modern Villas', 1, 'A sleek four-bedroom villa built around clean lines, expansive glazing, and an open-plan living core that flows straight onto a covered outdoor terrace.', 'Open-concept living\nFloor-to-ceiling windows\nCovered outdoor terrace\nDouble-height entry foyer'),
('Casa Horizon', 'casa-horizon', 980.00, 'MV-102', 3, 2.5, 1, 2, 2450.00, 62, 54, 'Slab', 'Low-Slope', 'Stucco & Wood Cladding', 'Modern Villas', 0, 'Single-story modern villa with a linear layout, wide overhangs for passive shading, and a private central courtyard.', 'Private central courtyard\nPassive solar shading\nOpen kitchen island\nWalk-in pantry'),
('Villa Solstice', 'villa-solstice', 1580.00, 'MV-103', 5, 4.5, 2, 3, 4100.00, 78, 64, 'Basement', 'Flat Roof', 'Concrete & Glass', 'Modern Villas', 1, 'A statement five-bedroom villa with cantilevered upper volumes, a rooftop terrace, and a three-bay garage for larger households.', 'Cantilevered second floor\nRooftop terrace\nHome theater room\nThree-bay garage'),
('The Cascade Villa', 'the-cascade-villa', 1120.00, 'MV-104', 4, 3.0, 2, 2, 3050.00, 66, 56, 'Slab', 'Flat Roof', 'Stone & Stucco', 'Modern Villas', 0, 'Split-level modern villa designed around a stepped facade and a landscaped side courtyard that brings light into every room.', 'Stepped split-level design\nLandscaped side courtyard\nDouble-height living room\nBuilt-in outdoor kitchen'),
('Villa Aurea', 'villa-aurea', 875.00, 'MV-105', 3, 2.0, 1, 2, 2100.00, 58, 50, 'Slab', 'Low-Slope', 'Stucco', 'Modern Villas', 0, 'Compact single-story villa plan optimized for narrow lots, with a private rear patio and efficient open living space.', 'Narrow-lot optimized\nPrivate rear patio\nEfficient open floor plan\nMudroom with storage'),
('The Monarch Villa', 'the-monarch-villa', 1750.00, 'MV-106', 5, 5.0, 3, 3, 4650.00, 82, 70, 'Basement', 'Flat Roof', 'Glass & Concrete', 'Modern Villas', 1, 'Three-story flagship villa with a private elevator, primary suite retreat, and panoramic glazing across all levels.', 'Private elevator\nPrimary suite retreat\nPanoramic glazing\nRooftop lounge with kitchenette'),
('Casa Linea', 'casa-linea', 1040.00, 'MV-107', 4, 3.0, 2, 2, 2800.00, 64, 55, 'Slab', 'Low-Slope', 'Wood Cladding & Stucco', 'Modern Villas', 0, 'A linear modern villa layout emphasizing indoor-outdoor connection, with sliding glass walls opening onto a covered patio.', 'Sliding glass wall system\nCovered patio living\nKitchen with waterfall island\nDedicated home office'),
('Villa Verde', 'villa-verde', 1195.00, 'MV-108', 4, 3.5, 2, 2, 3150.00, 67, 57, 'Slab', 'Flat Roof', 'Stucco & Stone Accents', 'Modern Villas', 0, 'Eco-conscious modern villa plan with green roof sections, rainwater harvesting provisions, and generous natural cross-ventilation.', 'Green roof sections\nRainwater harvesting ready\nCross-ventilation design\nSolar panel ready roof');
